### ISSUE TITLE
from pyowm.city import CityList

### ISSUE THREAD

**Issue by danst0** [ola-ct/weatherbot#1]
Hallo,

ich habe pyowm per pip3 installiert.
`from pyowm.city import CityList`

 führt zu
`ImportError: cannot import name 'CityList'`

Daniel

**Comment by 607011** [comment]
Das Projekt [weatherbot](https://github.com/ola-ct/weatherbot) verwendet nicht das per `pip3` installierbare `pyowm`, sondern ein eigenes Modul mit gleichem Namen. Vielleicht sollte ich das mal in [pyowm-micro](https://github.com/ola-ct/pyowm-micro) umbenennen; so heißt schließlich auch das Repository.

**Comment by danst0** [comment]
Ok. Installiert. Jetzt fehlte mir noch ein Beispiel für die config json. Insbesondere
`"openweathermap": {"api_key": "xxxxxx", ???}`

**Comment by 607011** [comment]
config.json-Beispiel:

```JSON
{
  "telegram_bot_token": "...",
  "timeout_secs": 3600,
  "authorized_users": [ 123456787, 123456789 ],
  "openweathermap": {
    "city_list": "./pyowm/city.list.reduced.json.bz2",
    "api_key": "0123456789abcdef..."
  },
  "verbose": true
}
```

`authorized_users`: Liste der Telegram-IDs, die den Bot nutzen dürfen
`telegram_bot_token`: [Telegram API Key](https://core.telegram.org/api/obtaining_api_id)
`openweathermap/api_key`: [OWM API Key](http://openweathermap.org/appid)

**Comment by danst0** [comment]
Danke für die schnelle Hilfe. Ich habe die city.lists aus dem pyowm-micro jetzt in das pyowm-Verzeichnis des Bots kopiert. Das Entpacken scheint noch nicht zu funktionieren...

`pi@kirby ~/weatherbot ❯❯❯ ls pyowm
city.de.list.reduced.json.bz2  city.list.reduced.json.bz2`

`pi@kirby ~/weatherbot ❯❯❯ ./weatherbot.py
Traceback (most recent call last):
  File "./weatherbot.py", line 350, in <module>
    main()
  File "./weatherbot.py", line 329, in main
    lambda p: print('\rLoading city list ... {:d}%'.format(p), end='', flush=True))
  File "/usr/local/lib/python3.4/dist-packages/pyowm_micro-1.0.3-py3.4.egg/pyowm/city.py", line 119, in read
  File "/usr/lib/python3.4/bz2.py", line 365, in readlines
    return io.BufferedIOBase.readlines(self, size)
  File "/usr/lib/python3.4/bz2.py", line 351, in readline
    return io.BufferedIOBase.readline(self, size)
  File "/usr/lib/python3.4/bz2.py", line 276, in peek
    if not self._fill_buffer():
  File "/usr/lib/python3.4/bz2.py", line 218, in _fill_buffer
    self._buffer = self._decompressor.decompress(rawblock)
OSError: Invalid data stream`
